language: ruby
bundler_args: --without development:production
before_script:
  - cp config/database.yml.sample config/database.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - RAILS_ENV=test bundle exec rake db:migrate
rvm:
  - 2.1.1
